export enum QueryKeys {
    // AI service
    AI_CHAT = 'aiChat',
    AI_SESSION = 'aiSession',
    // Chat service
    GROUP_CHATS = 'groupChats',
    CHAT_MESSAGES = 'chatMessages',
    // Media service
    MEDIAS = 'medias',
    NEW_MEDIAS = 'newMedias',
    MEDIA_BY_ID = 'mediaById',
    TOP_MEDIAS = 'topMedias',
    CATEGORIES = 'categories',
    TOP_CATEGORIES = 'topCategories',
    BOOKMARK_MEDIA = 'bookmarkMedia',
    LIKE_MEDIA = 'likeMedia',
    // Notification service
    NOTIFICATIONS = 'notifications',
    // User service
    USER = 'user',
    DOCTOR = 'doctor',
    HEALTH_RECORD = 'healthRecord',
    HEALTH_CARE_PLAN = 'healthCarePlan',
    CARE_PLAN_TEMPLATE = 'carePlanTemplate',
    SERVICE_PACKAGES = 'servicePackages',
    PURCHASED_SERVICE_PACKAGES = 'purchasedServicePackages',
    DOCTOR_LIST = 'doctorList',
    DOCTOR_SCHEDULE = 'doctorSchedule',
    SESSION_AMOUNT = 'sessionAmount',
    CONSULTATION_LIST = 'consultationList'
}